import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readlinkSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { parseYamlNested } from '../lib/core.mjs';
const ROOT = fileURLToPath(new URL('../', import.meta.url)), CLI = join(ROOT, 'bin/oats.mjs');
const SOURCE = 'git:ssh://onboard.invalid/framework.git', NAME = 'oats-setup-expert';
function fixture(t) {
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'oats-onboard-'))), repo = join(root, 'framework'), deployment = join(root, 'deployment'), home = join(root, 'operator'), bin = join(root, 'bin');
  for (const path of [repo, home, bin]) mkdirSync(path);
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const write = (path, value) => { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, typeof value === 'string' ? value : JSON.stringify(value)); };
  const config = join(home, 'gitconfig'), catalog = join(home, 'catalog.json'), effects = join(root, 'transport.log'), invoked = join(root, 'runtime-invoked');
  write(config, '[commit]\n  gpgsign = false\n');
  const ssh = join(bin, 'fixture-ssh');
  writeFileSync(ssh, `#!/bin/sh\nfor last do :; done\ncase "$last" in "git-upload-pack '/framework.git'") echo transport >> '${effects}'; exec git-upload-pack '${repo}';; *) exit 91;; esac\n`, { mode: 0o700 });
  writeFileSync(join(bin, 'pi'), `#!/bin/sh\necho invoked > '${invoked}'\nexit 98\n`, { mode: 0o700 });
  const env = { HOME: home, PATH: bin + ':' + process.env.PATH, GIT_CONFIG_GLOBAL: config, GIT_CONFIG_SYSTEM: '/dev/null', GIT_CONFIG_NOSYSTEM: '1', GIT_ALLOW_PROTOCOL: 'ssh', GIT_SSH_COMMAND: ssh, GIT_SSH_VARIANT: 'ssh', OATS_PACKAGE_CATALOG: catalog, SHELL: '/usr/bin/true' };
  const git = (...args) => execFileSync('git', ['-C', repo, ...args], { env, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git('init', '--quiet', '--initial-branch=fixture'); git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@example.invalid');
  git('config', 'uploadpack.allowFilter', 'true'); git('config', 'uploadpack.allowAnySHA1InWant', 'true');
  cpSync(join(ROOT, 'oats-package'), join(repo, 'oats-package'), { recursive: true, verbatimSymlinks: true, filter: path => !path.includes('/node_modules') });
  cpSync(join(ROOT, 'souls', NAME), join(repo, 'souls', NAME), { recursive: true, verbatimSymlinks: true });
  write(join(repo, 'oats.yaml'), { schemaVersion: 1, exports: { souls: [{ path: `souls/${NAME}`, definition: `souls/${NAME}/soul.yaml` }] } });
  write(join(repo, 'oats-workspace.yaml'), { schemaVersion: 1, name: 'Explicit fixture', imports: [] });
  git('add', '.'); git('commit', '--quiet', '-m', 'source-complete setup edition'); const commit = git('rev-parse', 'HEAD');
  write(catalog, { packages: { 'oats.framework': { url: SOURCE.slice(4), ref: commit, path: 'oats-package' } }, capabilities: { 'oats.core': 'oats.framework', 'oats.setup': 'oats.framework' } });
  const run = (args, extraEnv = {}) => {
    const child = spawnSync(process.execPath, [CLI, ...args], { cwd: root, env: { ...env, ...extraEnv }, encoding: 'utf8', timeout: 30000 });
    assert.equal(child.error, undefined, child.stderr); return { status: child.status, stdout: child.stdout, stderr: child.stderr, envelope: JSON.parse(child.stdout) };
  };
  return { root, repo, deployment, env, effects, invoked, catalog, write, git, commit, run };
}

test('onboard acquires and declares both capabilities, prints exact next command, then scaffolds five capability-owned skills without launching', t => {
  const f = fixture(t), result = f.run(['onboard', '--dir', f.deployment, '--json'], { OATS_DEPLOYMENT: '/poison', OATS_RESOLUTION: 'poison', PI_AGENTS_ROOT: '/poison/root' });
  assert.equal(result.status, 0, result.stdout + result.stderr); const r = result.envelope.result;
  assert.equal(r.mode, 'classic'); assert.equal(r.captured, false); assert.equal(r.launched, false); assert.equal(r.kind, 'local');
  const soul = parseYamlNested(readFileSync(join(r.soul, 'soul.yaml'), 'utf8'));
  assert.deepEqual(Object.keys(soul.requires.capabilities).sort(), ['oats.core', 'oats.setup']);
  for (const cap of Object.values(soul.requires.capabilities)) assert.equal(cap.source, `${SOURCE}@${f.commit}#oats-package`);
  assert.deepEqual(soul.defaults, { knowledge: 'none', messaging: 'none', tasks: 'none' });
  assert.equal(readlinkSync(join(r.soul, 'CLAUDE.md')), 'AGENTS.md');
  const lock = JSON.parse(readFileSync(r.lockFile)); assert.equal(lock.packages['oats.framework'].commit, f.commit);
  assert.deepEqual(Object.keys(lock.capabilities).sort(), ['oats.core', 'oats.knowledge-theory', 'oats.setup']);
  for (const row of Object.values(lock.capabilities)) assert.equal(row.trusted, false, 'catalog discovery never becomes executable trust');
  assert.equal(existsSync(f.invoked), false);
  const spawned = spawnSync(r.next.argv[0], [...r.next.argv.slice(1), '--no-launch', '--json'], { cwd: f.root, env: f.env, encoding: 'utf8', timeout: 15000 });
  assert.equal(spawned.status, 0, spawned.stdout + spawned.stderr); const s = JSON.parse(spawned.stdout).result;
  const meta = JSON.parse(readFileSync(join(s.home, 'instance.json')));
  assert.deepEqual(meta.skills.map(v => v.name).sort(), ['oats-config', 'oats-operate', 'oats-packages', 'oats-souls', 'oats-workspace-setup']);
  assert.ok(meta.skills.every(v => ['oats.core', 'oats.setup'].includes(v.source))); assert.equal(meta.launched, false);
  for (const skill of meta.skills) assert.deepEqual(readFileSync(join(s.home, '.agents/skills', skill.name, 'SKILL.md')),
    readFileSync(join(f.deployment, '.agents/capabilities/installed', skill.source, 'skills', skill.name, 'SKILL.md')), 'all five skill bodies are actually materialized from their capability');
  assert.equal(readlinkSync(join(s.home, 'CLAUDE.md')), 'AGENTS.md');
  assert.doesNotMatch(readFileSync(join(s.home, 'AGENTS.md'), 'utf8'), /<!-- oats:kernel:oats /);
  assert.equal(existsSync(f.invoked), false);
  const retired = f.run(['retire', s.instance, '--dir', f.deployment, '--json']);
  assert.equal(retired.status, 0, retired.stdout + retired.stderr); assert.equal(existsSync(s.home), false);
});

test('onboard refuses an existing roster before acquisition; force preserves agents/config and excludes unrelated hooks only for setup', t => {
  const f = fixture(t), soul = join(f.deployment, 'agents/existing/soul/soul.yaml'), config = join(f.deployment, 'oats-config.yaml');
  f.write(soul, 'name: existing\nkind: persistent\nwork: directory\n');
  f.write(join(dirname(soul), 'AGENTS.md'), '# Existing role\n'); symlinkSync('AGENTS.md', join(dirname(soul), 'CLAUDE.md'));
  const hook = join(f.root, 'unrelated-hook-ran'), cap = join(f.deployment, '.agents/capabilities/owned/other');
  f.write(join(cap, 'oats.json'), { capability: 'fixture.other', layer: 'knowledge', version: '1.0.0', description: 'Unrelated provider', hooks: { 'soul-scaffold': 'hook.mjs' } });
  f.write(join(f.deployment, '.agents/capabilities/owned/additive/oats.json'), { capability: 'fixture.additive', version: '1.0.0', description: 'Unrelated additive' });
  f.write(join(cap, 'hook.mjs'), `import {writeFileSync} from 'node:fs';writeFileSync(${JSON.stringify(hook)},'forbidden');`);
  f.write(config, 'name: existing-deployment\ncapabilities:\n  layers:\n    knowledge:\n      capability: fixture.other\n      global: true\n  additive:\n    fixture.additive:\n      global: true\n');
  const before = readFileSync(config, 'utf8'), soulBefore = readFileSync(soul, 'utf8');
  const refused = f.run(['onboard', '--dir', f.deployment, '--json']);
  assert.equal(refused.status, 1); assert.equal(refused.envelope.error.code, 'E_DEPLOYMENT_NOT_EMPTY');
  assert.equal(existsSync(f.effects), false); assert.equal(readFileSync(config, 'utf8'), before);
  const allowed = f.run(['onboard', '--dir', f.deployment, '--force-existing', '--json']);
  assert.equal(allowed.status, 0, allowed.stdout + allowed.stderr);
  assert.equal(readFileSync(soul, 'utf8'), soulBefore); assert.equal(existsSync(hook), false);
  const after = parseYamlNested(readFileSync(config, 'utf8'));
  assert.equal(after.name, 'existing-deployment'); assert.equal(after.capabilities.layers.knowledge.global, true);
  assert.equal(after.capabilities.layers.knowledge.souls[NAME], false);
  assert.equal(after.capabilities.additive['fixture.additive'].global, true);
  assert.equal(after.capabilities.additive['fixture.additive'].souls[NAME], false);
  const existing = f.run(['doctor', f.deployment, '--soul', 'existing', '--json']);
  assert.equal(existing.status, 0, existing.stdout + existing.stderr);
  assert.deepEqual(existing.envelope.capabilities.map(c => c.id).sort(), ['fixture.additive', 'fixture.other']);
  assert.equal(f.run(['onboard', '--dir', f.deployment, '--force-existing', '--json']).envelope.error.code, 'E_AGENT_EXISTS');
  const partial = join(f.root, 'partial'), evidence = join(partial, 'local-agents', NAME, 'soul/AGENTS.md');
  f.write(evidence, 'Preserved incomplete prior attempt'); const transportBefore = readFileSync(f.effects, 'utf8');
  assert.equal(f.run(['onboard', '--dir', partial, '--force-existing', '--json']).envelope.error.code, 'E_AGENT_EXISTS');
  assert.equal(readFileSync(evidence, 'utf8'), 'Preserved incomplete prior attempt');
  assert.equal(readFileSync(f.effects, 'utf8'), transportBefore, 'incomplete existing soul refuses before acquisition');
});

test('onboard copies the explicitly pinned workspace edition without adopting its policy or falling back from missing exports', t => {
  const f = fixture(t);
  f.write(join(f.repo, 'oats-workspace.yaml'), { schemaVersion: 1, name: 'Explicit fixture', imports: [{ source: SOURCE, revision: f.commit, soul: `souls/${NAME}`, alias: NAME }] });
  f.write(join(f.repo, 'souls', NAME, 'AGENTS.md'), 'CURRENT SOURCE MUST NOT REPLACE THE PINNED EDITION');
  f.git('add', '.'); f.git('commit', '--quiet', '-m', 'later workspace imports published earlier edition');
  const result = f.run(['onboard', '--dir', f.deployment, '--workspace', SOURCE, '--json']);
  assert.equal(result.status, 0, result.stdout + result.stderr); const r = result.envelope.result;
  assert.equal(r.source.kind, 'exported-edition-copy'); assert.equal(r.source.revision, f.commit);
  assert.notEqual(r.source.workspaceRevision, f.commit); assert.equal(r.captured, false);
  assert.doesNotMatch(readFileSync(join(r.soul, 'AGENTS.md'), 'utf8'), /CURRENT SOURCE MUST NOT/);
  const invalid = f.run(['onboard', '--dir', join(f.root, 'invalid'), '--workspace', 'repo:not-a-repository', '--json']);
  assert.equal(invalid.status, 1); assert.equal(existsSync(join(f.root, 'invalid')), false);
  f.write(join(f.repo, 'oats-workspace.yaml'), { schemaVersion: 1, name: 'Explicit fixture', imports: [] });
  f.write(join(f.repo, 'oats.yaml'), { schemaVersion: 1, exports: { souls: [] } });
  f.git('add', '.'); f.git('commit', '--quiet', '-m', 'no setup edition export at this revision');
  const missing = f.run(['onboard', '--dir', join(f.root, 'missing'), '--workspace', `${SOURCE}@${f.git('rev-parse', 'HEAD')}`, '--json']);
  assert.equal(missing.status, 1); assert.equal(missing.envelope.error.code, 'export-not-found');
  assert.equal(existsSync(join(f.root, 'missing')), false, 'failed explicit export never falls back to packaged default');
  const captured = f.run(['onboard', '--deployment', f.deployment, '--resolution', 'sha256-' + '1'.repeat(64), '--json']);
  assert.equal(captured.status, 1);
});

test('onboard does not turn a catalog entry into executable approval', t => {
  const f = fixture(t), cap = join(f.repo, 'oats-package/capabilities/oats-core'), manifest = JSON.parse(readFileSync(join(cap, 'oats.json')));
  manifest.hooks = { spawn: { command: 'danger.mjs', required: true } };
  f.write(join(cap, 'oats.json'), manifest);
  f.write(join(cap, 'danger.mjs'), `import {writeFileSync} from 'node:fs';writeFileSync(${JSON.stringify(f.invoked)},'forbidden');`);
  f.git('add', '.'); f.git('commit', '--quiet', '-m', 'unexpected executable surface');
  const catalog = JSON.parse(readFileSync(f.catalog)); catalog.packages['oats.framework'].ref = f.git('rev-parse', 'HEAD'); f.write(f.catalog, catalog);
  const result = f.run(['onboard', '--dir', f.deployment, '--json']);
  assert.equal(result.status, 1); assert.equal(result.envelope.error.code, 'approval-required');
  assert.equal(result.envelope.error.details.packageAcquired, false);
  assert.equal(existsSync(join(f.deployment, 'oats-lock.json')), false);
  assert.equal(existsSync(join(f.deployment, 'local-agents', NAME)), false);
  assert.equal(existsSync(f.invoked), false);
});
