#!/usr/bin/env node
// Turn-record conformance validator (docs/turn-record-sot.md).
//
// Dependency-free, Node >= 18. Independent re-implementation of canonical
// JSON, turn ids, did:key Ed25519 verification, the aweb projection, and the
// merge rules; the vectors are generated by the Python awid stack, so a green
// run is a two-language agreement on every byte.

import { createHash, createPublicKey, verify as edVerify } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------- canonical JSON

class CoreNumberError extends Error {}

function canon(v) {
  if (v === null) return "null";
  const t = typeof v;
  if (t === "string") return JSON.stringify(v);
  if (t === "boolean") return v ? "true" : "false";
  if (t === "number") {
    if (!Number.isInteger(v) || Math.abs(v) > Number.MAX_SAFE_INTEGER) {
      throw new CoreNumberError(`non-integer number in canonical core: ${v}`);
    }
    return String(v);
  }
  if (Array.isArray(v)) return "[" + v.map(canon).join(",") + "]";
  if (t === "object") {
    const keys = Object.keys(v).sort();
    return "{" + keys.map((k) => JSON.stringify(k) + ":" + canon(v[k])).join(",") + "}";
  }
  throw new Error(`unsupported value in canonical core: ${t}`);
}

function coreString(turn) {
  const core = {};
  for (const k of Object.keys(turn)) if (k !== "id" && k !== "sig") core[k] = turn[k];
  return canon(core);
}

function turnId(turn) {
  return "t1:" + createHash("sha256").update(coreString(turn), "utf8").digest("hex");
}

// ------------------------------------------------------- did:key + ed25519

const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

function b58decode(s) {
  let n = 0n;
  for (const c of s) {
    const i = B58.indexOf(c);
    if (i < 0) throw new Error(`invalid base58 char ${c}`);
    n = n * 58n + BigInt(i);
  }
  const bytes = [];
  while (n > 0n) {
    bytes.push(Number(n & 0xffn));
    n >>= 8n;
  }
  bytes.reverse();
  for (const c of s) {
    if (c === "1") bytes.unshift(0);
    else break;
  }
  return Uint8Array.from(bytes);
}

function publicKeyFromDid(did) {
  if (!did.startsWith("did:key:z")) throw new Error(`unsupported did ${did}`);
  const decoded = b58decode(did.slice("did:key:z".length));
  if (decoded[0] !== 0xed || decoded[1] !== 0x01 || decoded.length !== 34) {
    throw new Error(`not an ed25519 did:key: ${did}`);
  }
  const SPKI = Buffer.from("302a300506032b6570032100", "hex");
  return createPublicKey({
    key: Buffer.concat([SPKI, Buffer.from(decoded.subarray(2))]),
    format: "der",
    type: "spki",
  });
}

function b64decode(s) {
  const normalized = s.replaceAll("-", "+").replaceAll("_", "/");
  const padded = normalized + "=".repeat((4 - (normalized.length % 4)) % 4);
  return Buffer.from(padded, "base64");
}

function verifySig(did, payloadUtf8, sigB64) {
  return edVerify(null, Buffer.from(payloadUtf8, "utf8"), publicKeyFromDid(did), b64decode(sigB64));
}

// ------------------------------------------------------------- aweb project

function projectSigned(row, kind) {
  const p = JSON.parse(row.signed_payload);
  return {
    v: 1,
    ts: p.timestamp,
    from: p.from,
    to: p.to,
    thread: "aweb:conv:" + row.conversation_id,
    kind,
    body: { subject: p.subject, text: p.body },
    signature: row.signature,
    signed_payload: row.signed_payload,
    provenance: {
      source: kind === "mail" ? "aweb-mail" : "aweb-chat",
      fidelity: "projected",
      origin: { message_id: row.message_id, conversation_id: row.conversation_id },
    },
  };
}

function projectLegacy(row) {
  const origin = {
    message_id: row.message_id,
    conversation_id: row.conversation_id,
  };
  for (const k of ["from_did", "from_stable_id", "to_did", "to_stable_id", "priority"]) {
    if (row[k] !== undefined) origin[k] = row[k];
  }
  origin.timestamp_source = "created_at";
  return {
    v: 1,
    ts: row.created_at,
    from: row.from,
    to: row.to,
    thread: "aweb:conv:" + row.conversation_id,
    kind: "mail",
    body: { subject: row.subject, text: row.body },
    provenance: { source: "aweb-mail", fidelity: "projected", origin },
  };
}

function checkSignedConsistency(turn) {
  const p = JSON.parse(turn.signed_payload);
  const pairs = [
    [turn.ts, p.timestamp, "ts/timestamp"],
    [turn.from, p.from, "from"],
    [turn.to, p.to, "to"],
    [turn.body.subject, p.subject, "body.subject/subject"],
    [turn.body.text, p.body, "body.text/body"],
  ];
  for (const [a, b, what] of pairs) {
    if (a !== b) throw new Error(`signed consistency violation on ${what}`);
  }
}

function unproject(turn) {
  const out = {};
  if (turn.signed_payload !== undefined) {
    const p = JSON.parse(turn.signed_payload);
    Object.assign(out, p);
    out.message_id = turn.provenance.origin.message_id;
    out.conversation_id = turn.provenance.origin.conversation_id;
    out.signature = turn.signature;
    out.signed_payload = turn.signed_payload;
    if (p.message_id !== undefined && p.message_id !== out.message_id) {
      throw new Error("signed_payload message_id disagrees with origin");
    }
    if (p.conversation_id !== undefined && p.conversation_id !== out.conversation_id) {
      throw new Error("signed_payload conversation_id disagrees with origin");
    }
    return out;
  }
  const origin = turn.provenance.origin;
  out.message_id = origin.message_id;
  out.conversation_id = origin.conversation_id;
  for (const k of ["from_did", "from_stable_id", "to_did", "to_stable_id", "priority"]) {
    if (origin[k] !== undefined) out[k] = origin[k];
  }
  out.from = turn.from;
  out.to = turn.to;
  out.subject = turn.body.subject;
  out.body = turn.body.text;
  if (origin.timestamp_source === "created_at") out.created_at = turn.ts;
  return out;
}

// -------------------------------------------------------------- merge rules

function isPrefix(shorter, longer) {
  if (shorter.length > longer.length) return false;
  for (let i = 0; i < shorter.length; i++) {
    if (shorter[i].id !== longer[i].id) return false;
  }
  return true;
}

function mergeStreams(replicas) {
  const merged = {};
  for (const replica of Object.values(replicas)) {
    for (const [stream, copy] of Object.entries(replica.streams)) {
      const prev = merged[stream];
      if (!prev) {
        merged[stream] = copy;
        continue;
      }
      const [a, b] = prev.length <= copy.length ? [prev, copy] : [copy, prev];
      if (!isPrefix(a, b)) throw new Error(`non-prefix copies of stream ${stream}`);
      merged[stream] = b;
    }
  }
  return merged;
}

function effectiveRecord(merged, recordOwner) {
  const byId = new Map();
  for (const copy of Object.values(merged)) {
    for (const turn of copy) if (!byId.has(turn.id)) byId.set(turn.id, turn);
  }
  const hidden = new Set();
  for (const turn of byId.values()) {
    if (turn.kind !== "tombstone") continue;
    for (const link of turn.links ?? []) {
      if (link.rel !== "tombstones") continue;
      const target = byId.get(link.ref);
      if (!target) continue;
      if (turn.from === target.from || turn.from === recordOwner) hidden.add(target.id);
    }
  }
  return { byId, hidden };
}

// ------------------------------------------------------------------ harness

let failures = 0;
let checks = 0;

function assert(cond, label) {
  checks++;
  if (!cond) {
    failures++;
    console.error(`FAIL  ${label}`);
  }
}

function assertThrows(fn, label) {
  checks++;
  try {
    fn();
    failures++;
    console.error(`FAIL  ${label} (expected rejection, got acceptance)`);
  } catch {
    /* expected */
  }
}

function load(name) {
  return JSON.parse(readFileSync(join(HERE, name), "utf8"));
}

// turn-id-v1
{
  const doc = load("turn-id-v1.json");
  for (const c of doc.cases) {
    assert(coreString(c.turn) === c.expected_canonical_core, `${c.name}: canonical core bytes`);
    assert(turnId(c.turn) === c.expected_id, `${c.name}: id`);
    assert(c.turn.id === c.expected_id, `${c.name}: stored id`);
    if (c.turn.sig) {
      assert(
        verifySig(c.turn.sig.by, coreString(c.turn), c.turn.sig.sig),
        `${c.name}: envelope sig`,
      );
    }
  }
  for (const n of doc.negatives) {
    if (n.reject === "id") {
      assert(turnId(n.turn) !== n.turn.id, `${n.name}: id mismatch detected`);
    } else if (n.reject === "sig") {
      checks++;
      let ok = false;
      try {
        ok = verifySig(n.turn.sig.by, coreString(n.turn), n.turn.sig.sig);
      } catch {
        ok = false;
      }
      if (ok) {
        failures++;
        console.error(`FAIL  ${n.name}: invalid signature accepted`);
      }
    } else if (n.reject === "number") {
      assertThrows(() => coreString(n.turn), `${n.name}: float rejected from core`);
    } else {
      assert(false, `${n.name}: unknown negative kind ${n.reject}`);
    }
  }
}

// aweb-projection-v1
{
  const doc = load("aweb-projection-v1.json");
  for (const c of doc.cases) {
    const expected = c.expected_turn;
    const projected = expected.signed_payload
      ? projectSigned(c.row, expected.kind)
      : projectLegacy(c.row);
    assert(
      coreString(projected) === coreString(expected),
      `${c.name}: independent projection matches expected core bytes`,
    );
    assert(turnId(projected) === expected.id, `${c.name}: projected id`);

    if (expected.signed_payload) {
      assert(
        expected.signed_payload === c.row.signed_payload,
        `${c.name}: signed_payload byte-verbatim`,
      );
      const p = JSON.parse(expected.signed_payload);
      assert(
        verifySig(p.from_did, expected.signed_payload, expected.signature),
        `${c.name}: source signature verifies against from_did`,
      );
      checks++;
      try {
        checkSignedConsistency(expected);
      } catch (e) {
        failures++;
        console.error(`FAIL  ${c.name}: ${e.message}`);
      }
    }

    const row = unproject(expected);
    for (const f of c.round_trip_fields) {
      const want = c.row[f] !== undefined ? c.row[f] : JSON.parse(c.row.signed_payload ?? "{}")[f];
      assert(
        JSON.stringify(row[f]) === JSON.stringify(want),
        `${c.name}: round-trip field ${f}`,
      );
    }
  }
  for (const n of doc.negatives) {
    if (n.reject === "consistency") {
      assert(turnId(n.turn) === n.turn.id, `${n.name}: id itself is valid`);
      assertThrows(() => checkSignedConsistency(n.turn), `${n.name}: consistency rejected`);
    } else {
      assert(false, `${n.name}: unknown negative kind ${n.reject}`);
    }
  }
}

// journal-merge-v1
{
  const doc = load("journal-merge-v1.json");
  const merged = mergeStreams(doc.replicas);
  for (const [stream, len] of Object.entries(doc.expected.merged_stream_lengths)) {
    assert(merged[stream]?.length === len, `merge: stream ${stream} length ${len}`);
  }
  const { byId, hidden } = effectiveRecord(merged, doc.record_owner);
  assert(
    JSON.stringify([...byId.keys()].sort()) === JSON.stringify(doc.expected.union_ids),
    "merge: union ids",
  );
  assert(
    JSON.stringify([...hidden].sort()) === JSON.stringify([...doc.expected.hidden_ids].sort()),
    "merge: hidden ids (tombstone dominance + authority)",
  );
  const visible = [...byId.keys()].filter((id) => !hidden.has(id)).sort();
  assert(
    JSON.stringify(visible) === JSON.stringify(doc.expected.visible_ids),
    "merge: visible ids",
  );
  for (const t of byId.values()) {
    assert(turnId(t) === t.id, `merge: turn ${t.id.slice(0, 12)}… id recomputes`);
  }
  for (const n of doc.negatives) {
    if (n.reject === "prefix") {
      assertThrows(
        () =>
          mergeStreams({
            a: { streams: { [n.stream]: n.copy_a } },
            b: { streams: { [n.stream]: n.copy_b } },
          }),
        `${n.name}: non-prefix copies quarantined`,
      );
    } else {
      assert(false, `${n.name}: unknown negative kind ${n.reject}`);
    }
  }
}

if (failures) {
  console.error(`\n${failures}/${checks} checks failed`);
  process.exit(1);
}
console.log(`ok — ${checks} checks passed`);
