// Conformance against the turn-record vectors (docs/turn-record-sot.md in
// this package). The vectors were generated by the Python awid stack; this
// implementation must agree on every byte.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  CanonicalError,
  checkSignedConsistency,
  coreString,
  turnId,
  verifyDidKeySignature,
  verifyTurnId,
  verifyTurnSig,
} from "../lib/canonical.mjs";
import {
  projectLegacyRow,
  projectSignedRow,
  unprojectRow,
} from "../lib/project-aweb.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const load = (name) => JSON.parse(readFileSync(join(HERE, "vectors", name), "utf8"));

test("turn-id vectors: canonical bytes, ids, envelope signatures", () => {
  const doc = load("turn-id-v1.json");
  for (const c of doc.cases) {
    assert.equal(coreString(c.turn), c.expected_canonical_core, c.name);
    assert.equal(turnId(c.turn), c.expected_id, c.name);
    assert.ok(verifyTurnId(c.turn), c.name);
    if (c.turn.sig) assert.ok(verifyTurnSig(c.turn), `${c.name}: sig`);
  }
  for (const n of doc.negatives) {
    if (n.reject === "id") {
      assert.ok(!verifyTurnId(n.turn), n.name);
    } else if (n.reject === "sig") {
      assert.ok(!verifyTurnSig(n.turn), n.name);
    } else if (n.reject === "number") {
      assert.throws(() => coreString(n.turn), CanonicalError, n.name);
    } else {
      assert.fail(`${n.name}: unknown negative kind ${n.reject}`);
    }
  }
});

test("aweb projection vectors: projection, signatures, round-trip", () => {
  const doc = load("aweb-projection-v1.json");
  for (const c of doc.cases) {
    const expected = c.expected_turn;
    const projected = expected.signed_payload
      ? projectSignedRow(c.row, expected.kind)
      : projectLegacyRow(c.row);
    assert.equal(coreString(projected), coreString(expected), `${c.name}: core bytes`);
    assert.equal(projected.id, expected.id, `${c.name}: id`);

    if (expected.signed_payload) {
      assert.equal(expected.signed_payload, c.row.signed_payload, `${c.name}: verbatim payload`);
      const p = JSON.parse(expected.signed_payload);
      assert.ok(
        verifyDidKeySignature(p.from_did, expected.signed_payload, expected.signature),
        `${c.name}: source signature`,
      );
      checkSignedConsistency(expected);
    }

    const row = unprojectRow(expected);
    const payload = c.row.signed_payload ? JSON.parse(c.row.signed_payload) : {};
    for (const f of c.round_trip_fields) {
      const want = c.row[f] !== undefined ? c.row[f] : payload[f];
      assert.deepEqual(row[f], want, `${c.name}: round-trip ${f}`);
    }
  }
  for (const n of doc.negatives) {
    if (n.reject === "consistency") {
      assert.ok(verifyTurnId(n.turn), `${n.name}: id itself valid`);
      assert.throws(() => checkSignedConsistency(n.turn), CanonicalError, n.name);
    } else {
      assert.fail(`${n.name}: unknown negative kind ${n.reject}`);
    }
  }
});

test("signed consistency accepts a multi-recipient (array) to", () => {
  // `to` is string | string[] per the spec; equality must be by value.
  const payload = JSON.stringify({
    body: "b",
    from: "acme/alpha",
    from_did: "did:key:zX",
    subject: "s",
    timestamp: "2026-02-22T10:00:00Z",
    to: ["acme/beta", "acme/gamma"],
    type: "mail",
  });
  const turn = {
    v: 1,
    ts: "2026-02-22T10:00:00Z",
    from: "acme/alpha",
    to: ["acme/beta", "acme/gamma"],
    kind: "mail",
    body: { subject: "s", text: "b" },
    signed_payload: payload,
  };
  checkSignedConsistency(turn); // must not throw
  const reread = JSON.parse(JSON.stringify(turn)); // fresh array identity
  checkSignedConsistency(reread);
});

test("journal merge vectors: prefix rule, union, tombstone dominance", async (t) => {
  const { RecordStore } = await import("../lib/store.mjs");
  const { mkdtempSync, rmSync } = await import("node:fs");
  const { tmpdir } = await import("node:os");

  const doc = load("journal-merge-v1.json");
  const root = mkdtempSync(join(tmpdir(), "turn-record-merge-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const store = new RecordStore(root, { owner: doc.record_owner });

  // Replay both replicas into one store via mergeStreamCopy.
  for (const replica of Object.values(doc.replicas)) {
    for (const [streamId, turns] of Object.entries(replica.streams)) {
      store.mergeStreamCopy(streamId, turns);
    }
  }
  for (const [streamId, len] of Object.entries(doc.expected.merged_stream_lengths)) {
    assert.equal(store.readStream(streamId).length, len, `stream ${streamId}`);
  }
  const byId = store.readAll();
  assert.deepEqual([...byId.keys()].sort(), doc.expected.union_ids, "union ids");
  const hidden = store.hiddenIds(byId);
  assert.deepEqual([...hidden].sort(), [...doc.expected.hidden_ids].sort(), "hidden ids");
  const visible = [...byId.keys()].filter((id) => !hidden.has(id)).sort();
  assert.deepEqual(visible, doc.expected.visible_ids, "visible ids");

  for (const n of doc.negatives) {
    assert.equal(n.reject, "prefix", n.name);
    const nroot = mkdtempSync(join(tmpdir(), "turn-record-merge-neg-"));
    t.after(() => rmSync(nroot, { recursive: true, force: true }));
    const nstore = new RecordStore(nroot, { owner: doc.record_owner });
    nstore.mergeStreamCopy(n.stream, n.copy_a);
    assert.throws(() => nstore.mergeStreamCopy(n.stream, n.copy_b), /non-prefix/, n.name);
  }
});
